### ISSUE TITLE
Root directory entry

### ISSUE THREAD

**Issue by a1ip** [ExtraHop/metalsmith-sitemap#4]
Hello! Thank you for creating such a useful plugin. Here is my question: Is it a bug or a feature that **metalsmith-sitemap** doesn't generate entry for the root directory `<loc>hostname/</loc>`? I would like to add this important entry to my sitemap.xml. How can I do this?

**Comment by rnarian** [comment]
Just ran into the same problem. Any hints appreciated. :blush:

**Comment by rnarian** [comment]
I guess the problem is the missing `path` of the index page.

I wrote this little plugin to get around by setting the missing path to `/`. 

```js
var fixPath = function(prop, val) {
  return function(files, metalsmith, done) {

    for (var file in files) {
      if (files[file][prop] === val)
        files[file].path = '/';
    }

    done();
  };
};
```

Usage:

```js
.use(permalinks({ ... }))
.use(fixPath('title', 'Home'))
.use(sitemap({ ... }))
```

This checks if `file.title` === `Home` and sets path to `/`.

**Comment by boushley** [comment]
@rnarian Great workaround. If your root page doesn't have a path defined there isn't a ton this plugin can do since there could be multiple entries without a path.

@a1ip is your index page missing the path property as well?

That said if metalsmith for some reason doesn't include path on root maybe we should add that as a hard coded page.

Would adding a hardcoded `/` path with an option to disable resolve the issue?

**Comment by a1ip** [comment]
@boushley Yes, adding a hardcoded `/` path would resolve the issue.

**Comment by AoDev** [comment]
Hi, I wanted to say that I ran also into this issue. Since the homepage has no path, it's not added.

I also have a plugin that adds `/` as path to the root but this leads to a url that ends with `/`.

So instead of `http://mydomain.com`, I get `http://mydomain.com/` which is not what we want I'd say.

**Comment by arlair** [comment]
It sounds like it does not matter on the homepage. The root is the only one url that is treated the same with or without a trailing slash according to http://moz.com/community/q/trailing-slashes-on-home-pages

**Comment by eddywashere** [comment]
If anyone is interested in testing out my branch to address this #6, as well as some other updates #5, use my fork, develop branch 

```
npm install eddywashere/metalsmith-sitemap#develop
```

**Comment by boushley** [comment]
This is resoled as part of `0.1.0`

Thanks to @eddywashere for the fix!
